version: 2
jobs:
  test_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum “packages/football_trading/requirements.txt” }}
      - run:
          name: Running Tests
          command: |
            echo '$PROJECTSPATH'
            echo '$DB_DIR'
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/football_trading/requirements.txt
            export IN_PRODUCTION=false
            export PROJECTSPATH=/home/circleci/project/packages/football_trading
            export DB_DIR=/home/circleci/project/db.sqlite
            export BFEX_USER=$CCI_BFEX_USER
            export BFEX_PASSWORD=$CCI_BFEX_PASS
            export BFEX_APP_KEY=$CCI_BFEX_APP_KEY
            export BFEX_CERTS_PATH=$CCI_BFEX_CERTS_PATH
            export PRODUCTION_MODEL_NAME=match-predict-base
            export RECREATE_DB=false
            # Should we download any data here?
            py.test -vv packages/football_trading/tests
      - save_cache:
          keys:
            - py-deps-{{ checksum “packages/football_trading/requirements.txt” }}
          paths:
            - "/venv"
  train_and_upload_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum “packages/football_trading/requirements.txt” }}
      - run:
          name: Setup Environment
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/football_trading/requirements.txt
      - run:
          name: Train Model
          command: |
            echo '$PROJECTSPATH'
            echo '$DB_DIR'
            . venv/bin/activate
            export IN_PRODUCTION=false
            export PROJECTSPATH=/home/circleci/project/packages/football_trading
            export DB_DIR=/home/circleci/project/db.sqlite
            export BFEX_USER=$CCI_BFEX_USER
            export BFEX_PASSWORD=$CCI_BFEX_PASS
            export BFEX_APP_KEY=$CCI_BFEX_APP_KEY
            export BFEX_CERTS_PATH=$CCI_BFEX_CERTS_PATH
            export PRODUCTION_MODEL_NAME=match-predict-base
            export RECREATE_DB=false
            export PYTHONPATH=./packages/football_trading
            python ./packages/football_trading/football_trading/train.py
      - run:
          name: Publish Model
          command: |
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./packages/football_trading/
      - save_cache:
          keys:
            - py-deps-{{ checksum “packages/football_trading/requirements.txt” }}
          paths:
            - "/venv"
workflows:
  version: 2
  test-all:
    jobs:
      - test_model
      - train_and_upload_model
