version: 2
jobs:
  test_and_publish:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: py-deps-{{ checksum "packages/football_trading/requirements.txt" }}
      - run:
          name: Build Package & Test
          command: |
            chmod +x ./scripts/build_model_package.sh
            ./scripts/build_model_package.sh
      - run:
          name: Publish Model
          command: |
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./packages/football_trading/
      - save_cache:
          key: py-deps-{{ checksum "packages/football_trading/requirements.txt" }}
          paths:
            - "/venv"
      - store_test_results:
          path: test-results
  train_and_upload_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: py-deps-{{ checksum "packages/api/requirements.txt" }}
      - run:
          name: Setup Environment
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/api/requirements.txt
      - run:
          name: Train Model
          command: |
            chmod u+x ./scripts/train_model.sh
            ./scripts/train_model.sh
      - save_cache:
          key: py-deps-{{ checksum "packages/api/requirements.txt" }}
          paths:
            - "/venv"
  daily_predictions:
    working_directory: ~/project
    docker:
        - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: py-deps-{{ checksum "packages/api/requirements.txt" }}
      - run:
          name: Setup Environment
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/api/requirements.txt
      - run:
          name: Make Predictions
          command: |
            chmod u+x ./scripts/make_predictions.sh
            ./scripts/make_predictions.sh
      - save_cache:
          key: py-deps-{{ checksum "packages/api/requirements.txt" }}
          paths:
            - "/venv"
workflows:
  version: 2
  run-model-tests:
    # Run unit tests and train the model on the latest data (but dont upload anything)
    jobs:
      - test_and_publish:
          context: aws
  weekly-train:
    # Train the model using the latest version of the code via the API,
    # upload new model if it performs better than the old one
    jobs:
      - train_and_upload_model:
          context: aws
    triggers:
      - schedule:
          cron: "0 0 * * 3"  # Run every wednesday at midnight
          filters:
            branches:
              only:
                - master
  daily-predict:
    # Check and make predictions for any new fixtures that haven't been predicted for
    jobs:
      - daily_predictions:
          context: aws
#    triggers:
#      - schedule:
#          cron: "0 2 * * *"  # Run every day at 2am
#          filters:
#            branches:
#              only:
#                - master
