version: 2
jobs:
  test_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running Tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/football_trading/requirements.txt
            export PROJECTSPATH=$CCI_PROJECTSPATH
            export IN_PRODUCTION=false
            export BFEX_USER=$CCI_BFEX_USER
            export BFEX_PASS=$CCI_BFEX_PASS
            export BFEX_APP_KEY=$CCI_BFEX_APP_KEY
            export BFEX_CERTS_PATH=$CCI_BFEX_CERTS_PATH
            export RECREATE_DB=false
            # Should we download any data here?
            py.test -vv packages/football_trading/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_model